# Configuration for golangci-lint
# See: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: false # Don't lint test files by default

  skip-files:
    - ".*_test\\.go$" # Ignore all test files
    - "testutil/" # Ignore testutil directory (try without .go)
    - "testutil/**/*.go" # Ignore all Go files in testutil recursively
    - "internal/.*_test\\.go$" # Ignore test files in internal
    - "cmd/.*/.*_test\\.go$" # Ignore test files in cmd subdirs

  skip-dirs:
    - testutil # Skip entire testutil directory
    - vendor # Skip vendor directory
    - .git # Skip git directory

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  # Maximum count of issues with the same text
  max-same-issues: 10

  # Exclude specific linters for specific files
  exclude-rules:
    # Ignore errcheck in test files (double protection)
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
        - ineffassign
        - staticcheck
        - unused

    # Ignore specific linters in testutil (comprehensive)
    - path: "testutil/"
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - revive
        - govet
        - misspell

    # Ignore testutil subdirectories
    - path: "testutil/.*"
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - revive
        - govet
        - misspell

    # Ignore all gosec issues in testutil files
    - path: "testutil"
      linters:
        - gosec

    # More specific testutil exclusions
    - path: "testutil.*\\.go"
      linters:
        - gosec
        - errcheck
        - staticcheck
        - unused
        - ineffassign
        - revive
        - govet
        - misspell

    # Ignore specific issues by text
    - text: "Error return value of.*is not checked"
      linters:
        - errcheck

    # Ignore package comment requirements
    - text: "should have a package comment"
      linters:
        - revive

    # Ignore exported function comment requirements
    - text: "(exported|should have comment)"
      linters:
        - revive

linters:
  enable:
    - errcheck # Check for unchecked errors
    - staticcheck # Static analysis checks
    - unused # Unused code detection
    - ineffassign # Ineffectual assignments
    - govet # Go vet
    - misspell # Misspellings

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    check-type-assertions: false

    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    check-blank: false

    # List of functions to exclude from checking
    exclude-functions:
      - (*os.File).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      - (*github.com/testcontainers/testcontainers-go.Container).Terminate

  govet:
    # Report about shadowed variables
    check-shadowing: false

  misspell:
    # Correct spellings using locale preferences for US or UK
    locale: US

  revive:
    # Minimal confidence for issues
    min-confidence: 0
