version: 2

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  prerelease: auto
  draft: false
