version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vault-sync
    main: ./main.go
    binary: "vault-sync_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

snapshot:
  # Templates: allowed.
  version_template: "{{ .ShortCommit }}-devel"

archives:
  - id: vault-sync
    formats: ["tar.gz", "zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  abbrev: 0
  
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 🐛 Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 📚 Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 🔧 Improvements
      regexp: '^.*?(refactor|perf|style)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 🧪 Testing
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 🏗️ Build & CI
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: 🔒 Security
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: 📦 Dependencies
      regexp: '^.*?(deps|chore\(deps\))(\([[:word:]]+\))??!?:.+$'
      order: 7
    - title: 🔄 Other Changes
      order: 999

  filters:
    exclude:
      - '^chore:'
      - '^chore\(deps\):'
      - '^test:'
      - '^docs\(readme\):'
      - 'Merge pull request'
      - 'Merge remote-tracking branch'
      - 'Merge branch'
      - '^WIP:'
      - '^\[skip ci\]'
      - '^\[ci skip\]'

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/{{ .ProjectName | tolower }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/{{ .ProjectName | tolower }}:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64,linux/arm64"
    # Only tag as 'latest' for stable releases (not pre-releases)
    skip_push: false
    ids:
      - vault-sync

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    Welcome to this new release of vault-sync!
  footer: |
    ## Installation

    ### Binary
    Download the appropriate binary for your platform from the assets below.

    ### Docker
    ```bash
    docker pull ghcr.io/binsabbar/vault-sync:{{ .Tag }}
    ```

    ### Homebrew (coming soon)
    ```bash
    brew install binsabbar/tap/vault-sync
    ```

    ## Full Changelog
    See [CHANGELOG.md](https://github.com/binsabbar/vault-sync/blob/main/CHANGELOG.md) for details.
  extra_files:
    - glob: CHANGELOG.md
    - glob: README.md
    - glob: LICENSE
