# Start with the official Go image for building the application
FROM golang:1.24 as builder

# Set the working directory inside the container
WORKDIR /app/vault-sync

# Copy the Go modules manifests
COPY cmd/ /app/vault-sync/cmd
# COPY internal /app/vault-sync/internal
COPY  go.mod go.sum main.go /app/vault-sync/

RUN go mod verify && go mod tidy

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o vault-sync

# Use a minimal base image for the final container
FROM debian:stable-slim

# Set the working directory inside the container
WORKDIR /app/vault-sync

# Copy the built binary from the builder stage
COPY --from=builder /app/vault-sync/vault-sync .

# Set the entrypoint to the Go application
ENTRYPOINT ["./vault-sync"]